Now gtk3 and qt5. Added Mac version. Fixed script probs. Uses cmake now.

diff --git a/scripts/resetmsmice-enable-boot-linux b/scripts/resetmsmice-enable-boot-linux
--- a/scripts/resetmsmice-enable-boot-linux
+++ b/scripts/resetmsmice-enable-boot-linux
@@ -1,114 +1,119 @@
 #!/bin/sh
 
 find_it() {
-    WHICH1=`which $1 2> /dev/null`
-    if [ $? -eq 0 ]
-    then
-        LOC=`which $1 2> /dev/null | head -n 1`
-    else
-        [ -x /usr/local/sbin/$1 ] && LOC=/usr/local/sbin/$1
-        [ -z "$LOC" -a -x /usr/local/bin/$1 ] && LOC=/usr/local/bin/$1
-        [ -z "$LOC" -a -x /usr/sbin/$1 ] && LOC=/usr/sbin/$1
-        [ -z "$LOC" -a -x /usr/bin/$1 ] && LOC=/usr/bin/$1
-        [ -z "$LOC" -a -x /sbin/$1 ] && LOC=/sbin/$1
-        [ -z "$LOC" -a -x /bin/$1 ] && LOC=/bin/$1
-    fi
-    echo "$LOC"
+  WHICH1=`which $1 2> /dev/null`
+  if [ $? -eq 0 ]
+  then
+    LOC=`which $1 2> /dev/null | head -n 1`
+  else
+    [ -x /usr/local/sbin/$1 ] && LOC=/usr/local/sbin/$1
+    [ -z "$LOC" -a -x /usr/local/bin/$1 ] && LOC=/usr/local/bin/$1
+    [ -z "$LOC" -a -x /usr/sbin/$1 ] && LOC=/usr/sbin/$1
+    [ -z "$LOC" -a -x /usr/bin/$1 ] && LOC=/usr/bin/$1
+    [ -z "$LOC" -a -x /sbin/$1 ] && LOC=/sbin/$1
+    [ -z "$LOC" -a -x /bin/$1 ] && LOC=/bin/$1
+  fi
+  echo "$LOC"
 }
 
 
 check_status() {
-    # first check for systemd startup method
-    ps -C systemd > /dev/null
-    if [ $? -eq 0 -a -d /lib/systemd/system ]
+  # first check for systemd startup method
+  ps -C systemd > /dev/null
+  if [ $? -eq 0 -a -d /lib/systemd/system ]
+  then
+    SYSTEMCTL=`find_it systemctl`
+    if [ -n "$SYSTEMCTL" ]
     then
-        SYSTEMCTL=`find_it systemctl`
-        if [ -n "$SYSTEMCTL" ]
-        then
-            $SYSTEMCTL is-enabled resetmsmice.service > /dev/null 2>&1
-            if [ $? -eq 0 ] 
-            then
-                echo "ENABLED"
-                return 0
-            fi
-        fi
+      $SYSTEMCTL is-enabled resetmsmice.service > /dev/null 2>&1
+      if [ $? -eq 0 ] 
+      then
+        echo "ENABLED"
+        return 0
+      fi
     fi
+  fi
 
-    # check for upstart scripts
-    if [ -d /etc/init ]
+  # check systemd scripts
+  if [ -x /etc/init.d/resetmsmice ] 
+  then
+    [ -f /etc/rc2.d/S17resetmsmice ] && SYSV_ENABLED=1
+    [ -f /etc/rc3.d/S17resetmsmice ] && SYSV_ENABLED=1
+    [ -f /etc/rc4.d/S17resetmsmice ] && SYSV_ENABLED=1
+    [ -f /etc/rc5.d/S17resetmsmice ] && SYSV_ENABLED=1
+    if [ -n "$SYSV_ENABLED" ]
     then
-        INITCTL=`find_it initctl`
-        if [ -n "$INITCTL" ]
-        then
-            temp_file=`mktemp`
-            $INITCTL list > $temp_file
-            if [ $? -eq 0 ]
-            then
-                line_count=`wc -l $temp_file | cut -d' ' -f1`
-                rm $temp_file
-                if [ "$line_count" -ge 5 ]
-                then
-                    start_on=`$INITCTL show-config resetmsmice | grep -q "^  start on"`
-                    if [ $? -eq 0 ]
-                    then
-                        echo "ENABLED"
-                        return 0
-                    fi
-                fi
-            fi
-        fi
+      echo "ENABLED"
+      return 0
     fi
+  fi
 
-    if [ -x /etc/init.d/resetmsmice ] 
+  # check for upstart scripts
+  if [ -d /etc/init ]
+  then
+    INITCTL=`find_it initctl`
+    if [ -n "$INITCTL" ]
     then
-        [ -f /etc/rc2.d/S17resetmsmice ] && SYSV_ENABLED=1
-        [ -f /etc/rc3.d/S17resetmsmice ] && SYSV_ENABLED=1
-        [ -f /etc/rc4.d/S17resetmsmice ] && SYSV_ENABLED=1
-        [ -f /etc/rc5.d/S17resetmsmice ] && SYSV_ENABLED=1
-        if [ -n "$SYSV_ENABLED" ]
+      temp_file=`mktemp`
+      $INITCTL list > $temp_file
+      if [ $? -eq 0 ]
+      then
+        line_count=`wc -l $temp_file | cut -d' ' -f1`
+        rm $temp_file
+        if [ "$line_count" -ge 5 ]
         then
+          start_on=`$INITCTL show-config resetmsmice | grep -q "^  start on"`
+          if [ $? -eq 0 ]
+          then
             echo "ENABLED"
             return 0
+          fi
         fi
+      fi
     fi
-    echo "DISABLED"
-    return 0
+  fi
+  
+  echo "DISABLED"
+  return 0
 }
 
 
 enable_auto() {
-    disable_all --quiet
-    # first check for systemd startup method
-    ps -C systemd > /dev/null
-    if [ $? -eq 0 -a -d /lib/systemd/system ]
-    then
-        enable_systemd
-        return $?
-    fi
+  disable_all --quiet
+  # first check for systemd startup method
+  ps -C systemd > /dev/null
+  if [ $? -eq 0 -a -d /lib/systemd/system ]
+  then
+    enable_systemd
+    return $?
+  fi
 
-    # check for upstart scripts
-    if [ -d /etc/init ]
-    then
-        INITCTL=`find_it initctl`
-        if [ -n "$INITCTL" ]
-        then
-            temp_file=`mktemp`
-            $INITCTL list > $temp_file
-            if [ $? -eq 0 ]
-            then
-                line_count=`wc -l $temp_file | cut -d' ' -f1`
-                rm $temp_file
-                if [ "$line_count" -ge 5 ]
-                then
-                    enable_upstart
-                    return $?
-                fi
-            fi
-        fi
-    fi
-
+  if [ -d /etc/init.d ]
+  then
     enable_sysv
     return $?
+  fi
+
+  # check for upstart scripts
+  if [ -d /etc/init ]
+  then
+    INITCTL=`find_it initctl`
+    if [ -n "$INITCTL" ]
+    then
+       temp_file=`mktemp`
+       $INITCTL list > $temp_file
+       if [ $? -eq 0 ]
+       then
+          line_count=`wc -l $temp_file | cut -d' ' -f1`
+          rm $temp_file
+          if [ "$line_count" -ge 5 ]
+          then
+             enable_upstart
+             return $?
+          fi
+       fi
+    fi
+  fi
 }
 
 
@@ -156,6 +161,7 @@ console output" > /etc/init/resetmsmice.conf
 	fi
 }
 
+
 enable_systemd() {
 	RESETMSMICE=`find_it resetmsmice`
 	disable_systemd
@@ -184,25 +190,25 @@ Type=oneshot
 
 [Install]
 WantedBy=graphical.target" > /lib/systemd/system/resetmsmice.service
-    if [ $? -eq 0 ]
+  if [ $? -eq 0 ]
+  then
+    SYSTEMCTL=`find_it systemctl`
+    if [ -n "$SYSTEMCTL" ]
     then
-        SYSTEMCTL=`find_it systemctl`
-        if [ -n "$SYSTEMCTL" ]
-        then
-            $SYSTEMCTL enable resetmsmice.service
-            if [ $? -eq 0 ] 
-            then
-                echo "Complete!"
-                return 0
-            else
-                echo "Failed to setup resetmsmice service on startup."
-                exit 3
-            fi
-        fi
-    else
-        echo "Installation failed writing to '/lib/systemd/system/resetmsmice.service'!"
+      $SYSTEMCTL enable resetmsmice.service
+      if [ $? -eq 0 ] 
+      then
+        echo "Complete!"
+        return 0
+      else
+        echo "Failed to setup resetmsmice service on startup."
         exit 3
-    fi
+     fi
+  fi
+  else
+    echo "Installation failed writing to '/lib/systemd/system/resetmsmice.service'!"
+    exit 3
+  fi
 }
 
 
@@ -268,6 +274,7 @@ esac
 	fi
 }
 
+
 disable_all() {
 	disable_systemd
 	rm -f /etc/init/resetmsmice.conf
@@ -299,32 +306,44 @@ disable_all() {
     fi
 }
 
+
 disable_systemd() {
 	if [ -f /etc/systemd/system/resetmsmice.service -o -f /lib/systemd/system/resetmsmice.service ]
 	then
-                SYSTEMCTL=`find_it systemctl`
-                if [ -n "$SYSTEMCTL" ]
-                then
-                    $SYSTEMCTL disable resetmsmice.service
-                    rm -f /etc/systemd/system/resetmsmice.service
-                    rm -f /lib/systemd/system/resetmsmice.service
-                fi
+    SYSTEMCTL=`find_it systemctl`
+    if [ -n "$SYSTEMCTL" ]
+    then
+      $SYSTEMCTL disable resetmsmice.service
+      rm -f /etc/systemd/system/resetmsmice.service
+      rm -f /lib/systemd/system/resetmsmice.service
+    fi
 	fi
 }
 
+
+program_syntax() {
+  echo "Usage: resetmsmice-enable-boot [option]"
+	echo "Needs just one of the following two options:"
+  echo "  --enable        enable resetmsmice to run each time linux boots up"
+  echo "                  this script will automatically detect what type of"
+  echo "                  startup scripts your system uses"
+  echo "  --disable       stop resetting the mouse on bootup"
+  echo "  --status        check to see if resetmsmice is set to run on boot"
+}
 
 
 case "$1" in
 
 --enable) enable_auto 
-          errors=$?
-          if [ "$errors" -eq 0 -a ! "$2" = "--quiet" ]
-          then
-              echo "If you want to fix your mouse right now, instead of waiting to reboot your PC, just run: resetmsmice or resetmsmice-gui"
-              echo ""
-          fi 
-          exit $errors
-          ;;
+    errors=$?
+    if [ "$errors" -eq 0 -a ! "$2" = "--quiet" ]
+    then
+        echo "If you want to fix your mouse right now, instead of waiting to reboot your PC, just run: resetmsmice or resetmsmice-gui"
+        echo ""
+    fi 
+    exit $errors
+    ;;
+
 --status) check_status ;;
 
 --upstart) enable_upstart ;;
@@ -335,14 +354,7 @@ case "$1" in
 
 --disable) disable_all $2 ;;
 
-*)	echo "Usage: resetmsmice-boot [option]"
-	echo "Needs just one of the following two options:"
-    echo "  --enable        enable resetmsmice to run each time linux boots up"
-    echo "                  this script will automatically detect what type of"
-    echo "                  startup scripts your system uses"
-    echo "  --disable       stop resetting the mouse on bootup"
-    echo "  --status        check to see if resetmsmice is set to run on boot"
-	;;
+*) program_syntax ;;
 
 esac
 
